
sql.wirelessinfo_group.group.select = main,select corp_id,create_id, group_name,order_by,group_id  from wirelessinfo_group t where corp_id = ${corp_id} and enable = 1 order by group_name

sql.wirelessinfo_group.group_id.target_id.select.count = main,select count(*) from wirelessinfo_group_target wgt, wirelessinfo_group wg, axiom_target t where wgt.target_id = t.target_id and wgt.group_id = wg.group_id and wg.enable = 1 and wgt.group_id = ? order by wgt.rowid desc

sql.wirelessinfo_group.group_id.target_id.select.page = main,select * from (select a.*,rownum row_num from ( select t.target_id, t.corp_id, t.target_name from wirelessinfo_group_target wgt, wirelessinfo_group wg, axiom_target t where wgt.target_id = t.target_id and wgt.group_id = wg.group_id and wg.enable = 1 and wgt.group_id = ? order by wgt.rowid desc) a ) b where  b.row_num between ? and ?

sql.wirelessinfo_group.user_id.target_id.select.page = main,select * from (select a.*,rownum row_num from ( select ut.target_id, ut.target_name  from  (select t.target_id, t.corp_id, t.target_name, t.terminal_id from  (select target_id, corp_id, target_name, terminal_id from axiom_target  where corp_id in (select corp_id from axiom_corp start with corp_id = ${corp_id} connect by prior corp_id = parent_id)) t  where t.target_id not in (select target_id from axiom_group_target) order by t.target_name) ut,  axiom_terminal atm, axiom_terminal_type atmt where ut.terminal_id = atm.terminal_id    and atm.terminal_type_id = atmt.terminal_type_id   union   select ut.target_id, ut.target_name  from  (select target_id, group_id, target_name, terminal_id from  (select at.target_id, t.group_id, at.target_name, at.terminal_id from axiom_target at,  (select target_id, group_id from axiom_group_target where group_id in  (select group_id from axiom_group where corp_id in  (select corp_id from axiom_corp start with corp_id =  (select corp_id from axiom_user where user_id = ${user_id} and status = 1) connect by prior corp_id = parent_id))) t  where at.target_id = t.target_id  union  select att.target_id, agt.group_id, att.target_name, att.terminal_id  from axiom_target att, axiom_group_target agt, axiom_user_group   aug   where agt.target_id = att.target_id and agt.group_id = aug.group_id and aug.user_id = ${user_id}) order by target_name) ut, axiom_terminal atm,axiom_terminal_type atmt where ut.terminal_id = atm.terminal_id   and atm.terminal_type_id = atmt.terminal_type_id  Minus  select t.target_id, t.target_name from wirelessinfo_group_target wgt, wirelessinfo_group wg, axiom_target t where wgt.target_id = t.target_id and wgt.group_id = wg.group_id and wg.enable = 1 ) a order by a.target_name desc) b where  b.row_num between ? and ?

sql.wirelessinfo_group.user_id.target_id.select.count =  main,select count(*) from ( select ut.target_id, ut.target_name  from  (select t.target_id, t.corp_id, t.target_name, t.terminal_id from  (select target_id, corp_id, target_name, terminal_id from axiom_target  where corp_id in (select corp_id from axiom_corp start with corp_id = 163 connect by prior corp_id = parent_id)) t  where t.target_id not in (select target_id from axiom_group_target) order by t.target_name) ut,  axiom_terminal atm, axiom_terminal_type atmt where ut.terminal_id = atm.terminal_id    and atm.terminal_type_id = atmt.terminal_type_id    union   select ut.target_id, ut.target_name  from  (select target_id, group_id, target_name, terminal_id from  (select at.target_id, t.group_id, at.target_name, at.terminal_id from axiom_target at,  (select target_id, group_id from axiom_group_target where group_id in  (select group_id from axiom_group where corp_id in  (select corp_id from axiom_corp start with corp_id =  (select corp_id from axiom_user where user_id = 252 and status = 1) connect by prior corp_id = parent_id))) t  where at.target_id = t.target_id  union  select att.target_id, agt.group_id, att.target_name, att.terminal_id  from axiom_target att, axiom_group_target agt, axiom_user_group   aug   where agt.target_id = att.target_id and agt.group_id = aug.group_id and aug.user_id = 252) order by target_name) ut, axiom_terminal atm,axiom_terminal_type atmt where ut.terminal_id = atm.terminal_id   and atm.terminal_type_id = atmt.terminal_type_id  Minus  select t.target_id, t.target_name from wirelessinfo_group_target wgt, wirelessinfo_group wg, axiom_target t where wgt.target_id = t.target_id and wgt.group_id = wg.group_id and wg.enable = 1 )

sql.wirelessinfo_group.group.insert = main,insert into wirelessinfo_group (group_id, group_name, enable, create_id, corp_id) values (WIRELESSINFO_SEQ_GROUP_ID.Nextval, ?, 1, ${user_id}, ${corp_id} )

sql.wirelessinfo_group.group.delete = main,update wirelessinfo_group set  enable = 0 where group_id = ?


sql.wirelessinfo_group_target.insert = main,insert into wirelessinfo_group_target (group_id, target_id) values (?, ?)


sql.wirelessinfo_group_target.delete = main,delete wirelessinfo_group_target where target_id = ?




sql.wirelessinfo_group.user_id.target_id.params.select.page = main,select * from (select a.*,rownum row_num from ( select ut.target_id, ut.target_name  from  (select t.target_id, t.corp_id, t.target_name, t.terminal_id from  (select target_id, corp_id, target_name, terminal_id from axiom_target  where corp_id in (select corp_id from axiom_corp start with corp_id = ${corp_id} connect by prior corp_id = parent_id)) t  where t.target_id not in (select target_id from axiom_group_target) order by t.target_name) ut,  axiom_terminal atm, axiom_terminal_type atmt where ut.terminal_id = atm.terminal_id    and atm.terminal_type_id = atmt.terminal_type_id   union   select ut.target_id, ut.target_name  from  (select target_id, group_id, target_name, terminal_id from  (select at.target_id, t.group_id, at.target_name, at.terminal_id from axiom_target at,  (select target_id, group_id from axiom_group_target where group_id in  (select group_id from axiom_group where corp_id in  (select corp_id from axiom_corp start with corp_id =  (select corp_id from axiom_user where user_id = ${user_id} and status = 1) connect by prior corp_id = parent_id))) t  where at.target_id = t.target_id  union  select att.target_id, agt.group_id, att.target_name, att.terminal_id  from axiom_target att, axiom_group_target agt, axiom_user_group   aug   where agt.target_id = att.target_id and agt.group_id = aug.group_id and aug.user_id = ${user_id}) order by target_name) ut, axiom_terminal atm,axiom_terminal_type atmt where ut.terminal_id = atm.terminal_id   and atm.terminal_type_id = atmt.terminal_type_id  Minus  select t.target_id, t.target_name from wirelessinfo_group_target wgt, wirelessinfo_group wg, axiom_target t where wgt.target_id = t.target_id and wgt.group_id = wg.group_id and wg.enable = 1 ) a where  (upper(a.target_name)like '%' ||upper(?)|| '%' or 1=?) order by a.target_name desc) b where  b.row_num between ? and ?

sql.wirelessinfo_group.user_id.target_id.params.select.count =  main,select count(*) from ( select ut.target_id, ut.target_name  from  (select t.target_id, t.corp_id, t.target_name, t.terminal_id from  (select target_id, corp_id, target_name, terminal_id from axiom_target  where corp_id in (select corp_id from axiom_corp start with corp_id = 163 connect by prior corp_id = parent_id)) t  where t.target_id not in (select target_id from axiom_group_target) order by t.target_name) ut,  axiom_terminal atm, axiom_terminal_type atmt where ut.terminal_id = atm.terminal_id    and atm.terminal_type_id = atmt.terminal_type_id    union   select ut.target_id, ut.target_name  from  (select target_id, group_id, target_name, terminal_id from  (select at.target_id, t.group_id, at.target_name, at.terminal_id from axiom_target at,  (select target_id, group_id from axiom_group_target where group_id in  (select group_id from axiom_group where corp_id in  (select corp_id from axiom_corp start with corp_id =  (select corp_id from axiom_user where user_id = 252 and status = 1) connect by prior corp_id = parent_id))) t  where at.target_id = t.target_id  union  select att.target_id, agt.group_id, att.target_name, att.terminal_id  from axiom_target att, axiom_group_target agt, axiom_user_group   aug   where agt.target_id = att.target_id and agt.group_id = aug.group_id and aug.user_id = 252) order by target_name) ut, axiom_terminal atm,axiom_terminal_type atmt where ut.terminal_id = atm.terminal_id   and atm.terminal_type_id = atmt.terminal_type_id  Minus  select t.target_id, t.target_name from wirelessinfo_group_target wgt, wirelessinfo_group wg, axiom_target t where wgt.target_id = t.target_id and wgt.group_id = wg.group_id and wg.enable = 1 ) where (upper(target_name)like '%' ||upper(?)|| '%' or 1=?)
