sql.wirelessinfo.wirelessinfo_list.state.update =  main,update wirelessinfo_release set states=? where ref_release_id=?
sql.wirelessinfo.wirelessinfo_list_op.insert =  main,insert into WIRELESSINFO_RELEASE_OP(release_id, release_num, content_type, text, customer_id, start_time, end_time, play_start_time, play_end_time, isdelete, cost, create_time, release_cost, path, ref_release_id, states, info_class, release_type, reg_user_id, corp_id )  values(   WIRELESSINFO_RELEASE_OP_SEQ_ID.Nextval,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?,?,?)



sql.wirelessinfo.wirelessinfo_list.select.count =  main,select count(*) from (select t.release_id, t.release_num, t.content_type, t.start_time, t.end_time, t.play_start_time, t.play_end_time, t.text, t.customer_id, t.states, t.create_time, t.cost, t.info_class, t.release_type, t.reg_user_id, t.release_cost, t.path, t.ref_release_id, t.corp_id, t.isdelete, wc.customer_name from wirelessinfo_release t, wirelessinfo_customer wc where wc.customer_id = t.customer_id and t.corp_id=${corp_id} and t.reg_user_id=${user_id} and t.isdelete = 0 union select tr.ref_release_id as release_id, tr.release_num, tr.content_type, tr.start_time, tr.end_time, tr.play_start_time, tr.play_end_time, tr.text, tr.customer_id, tr.states, tr.create_time, tr.cost, tr.info_class, tr.release_type, tr.reg_user_id, tr.release_cost, tr.path,  tr.ref_release_id, tr.corp_id, tr.isdelete, wc.customer_name from wirelessinfo_release_op tr, wirelessinfo_customer wc where wc.customer_id = tr.customer_id and tr.corp_id=${corp_id} and tr.reg_user_id=${user_id} and tr.isdelete = 0)
sql.wirelessinfo.wirelessinfo_list.select.page =  main,select * from (select a.* ,rownum row_num from (select t.release_id, t.release_num, t.content_type, t.start_time, t.end_time, t.play_start_time, t.play_end_time, t.text, t.customer_id, t.states, t.create_time, t.cost, t.info_class, t.release_type, t.reg_user_id, t.release_cost, t.path, t.ref_release_id, t.corp_id, t.isdelete, wc.customer_name,t.path_name from wirelessinfo_release t, wirelessinfo_customer wc where wc.customer_id = t.customer_id and t.corp_id=${corp_id} and t.reg_user_id=${user_id} and t.isdelete = 0 union select tr.ref_release_id as release_id, tr.release_num, tr.content_type, tr.start_time, tr.end_time, tr.play_start_time, tr.play_end_time, tr.text, tr.customer_id, tr.states, tr.create_time, tr.cost, tr.info_class, tr.release_type, tr.reg_user_id, tr.release_cost, tr.path,  tr.ref_release_id, tr.corp_id, tr.isdelete, wc.customer_name,tr.path_name from wirelessinfo_release_op tr, wirelessinfo_customer wc where wc.customer_id = tr.customer_id and tr.corp_id=${corp_id} and tr.reg_user_id=${user_id} and  tr.isdelete = 0 order by release_id) a ) b where  b.row_num between ? and ?

sql.wirelessinfo.wirelessinfo_list_op.isdelete.update =  main,update wirelessinfo_release t set t.isdelete = 1 where t.release_id =?



sql.wirelessinfo.wirelessinfo_list_op.wirelessinfo_release_op.ref_release_id.update =  main,update wirelessinfo_release_op set ref_release_id=? where ref_release_id =?
sql.wirelessinfo.wirelessinfo_list_op.wirelessinfo_release_op.isdelete.update = main,update wirelessinfo_release_op t set t.isdelete = 1 where t.ref_release_id =?

sql.wirelessinfo.wirelessinfo_list.wirelessinfo_release_op.state.update = main,update wirelessinfo_release_op set states=? where ref_release_id=?


sql.wirelessinfo.wirelessinfo_list.conditions.select.count =  main,select count(*) from (select t.release_id, t.release_num, t.content_type, t.start_time, t.end_time, t.play_start_time, t.play_end_time, t.text, t.customer_id, t.states, t.create_time, t.cost, t.info_class, t.release_type, t.reg_user_id, t.release_cost, t.path, t.ref_release_id, t.corp_id, t.isdelete, wc.customer_name from wirelessinfo_release t, wirelessinfo_customer wc where wc.customer_id = t.customer_id and t.corp_id=${corp_id} and t.reg_user_id=${user_id} and t.isdelete = 0 union select tr.ref_release_id as release_id, tr.release_num, tr.content_type, tr.start_time, tr.end_time, tr.play_start_time, tr.play_end_time, tr.text, tr.customer_id, tr.states, tr.create_time, tr.cost, tr.info_class, tr.release_type, tr.reg_user_id, tr.release_cost, tr.path,  tr.ref_release_id, tr.corp_id, tr.isdelete, wc.customer_name from wirelessinfo_release_op tr, wirelessinfo_customer wc where wc.customer_id = tr.customer_id and tr.corp_id=${corp_id} and tr.reg_user_id=${user_id} and tr.isdelete = 0) wr  where (upper(wr.release_num)like '%' ||upper(?)|| '%' or 1=?)and (wr.start_time>= ? or 1=?) and (wr.end_time<= ? or 1=?)
sql.wirelessinfo.wirelessinfo_list.conditions.select.page =  main,select * from (select a.* ,rownum row_num from (select wr.release_id,wr.release_num,wr.content_type, wr.start_time,wr.end_time, wr.play_start_time,wr.play_end_time,wr.text,wr.customer_id, wr.states,wr.create_time, wr.cost,wr.info_class, wr.release_type, wr.reg_user_id, wr.release_cost, wr.path, wr.ref_release_id, wr.corp_id, wr.isdelete, wr.customer_name,wr.path_name from (select t.release_id, t.release_num, t.content_type, t.start_time, t.end_time, t.play_start_time, t.play_end_time, t.text, t.customer_id, t.states, t.create_time, t.cost, t.info_class, t.release_type, t.reg_user_id, t.release_cost, t.path, t.ref_release_id, t.corp_id, t.isdelete, wc.customer_name,t.path_name from wirelessinfo_release t, wirelessinfo_customer wc where wc.customer_id = t.customer_id and t.corp_id=${corp_id} and t.reg_user_id=${user_id} and t.isdelete = 0 union select tr.ref_release_id as release_id, tr.release_num, tr.content_type, tr.start_time, tr.end_time, tr.play_start_time, tr.play_end_time, tr.text, tr.customer_id, tr.states, tr.create_time, tr.cost, tr.info_class, tr.release_type, tr.reg_user_id, tr.release_cost, tr.path,  tr.ref_release_id, tr.corp_id, tr.isdelete, wc.customer_name,tr.path_name from wirelessinfo_release_op tr, wirelessinfo_customer wc where wc.customer_id = tr.customer_id and tr.corp_id=${corp_id} and tr.reg_user_id=${user_id} and  tr.isdelete = 0 order by release_id) wr where (upper(wr.release_num)like '%' ||upper(?)|| '%' or 1=?)and (wr.start_time>= ? or 1=?) and (wr.end_time<= ? or 1=?) order by wr.release_id) a ) b where  b.row_num between ? and ?


