
sql.wirelessinfo.wirelessinfo_publish_binding.conditions.select.count =  main,select count(*) from wirelessinfo_release_op wr where wr.corp_id =${corp_id} and (upper(wr.release_num)like '%' ||upper(?)|| '%' or 1=?)and (wr.start_time>= ? or 1=?) and (wr.end_time<= ? or 1=?) and wr.isdelete=0 and wr.states<>0
sql.wirelessinfo.wirelessinfo_publish_binding.conditions.select.page =  main,select * from (select a.* ,rownum row_num from (select wr.release_id,wr.release_num,wr.content_type,wr.start_time,wr.end_time,wr.play_start_time,wr.play_end_time,wr.text,wr.customer_id,wr.states,wr.create_time,wr.cost,wr.info_class, wr.release_type,wr.reg_user_id,wr.release_cost, wr.path, wr.ref_release_id,wr.corp_id,wr.isdelete,wc.customer_name from wirelessinfo_release_op wr,wirelessinfo_customer wc where wr.corp_id =${corp_id} and wc.customer_id=wr.customer_id and (upper(wr.release_num)like '%' ||upper(?)|| '%' or 1=?)and (wr.start_time>= ? or 1=?) and (wr.end_time<= ? or 1=?) and wr.isdelete=0 and wr.states<>0 order by release_id asc ) a ) b where  b.row_num between ? and ?

sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_group.select.count =  main,select count(*) from wirelessinfo_group where corp_id =${corp_id} and enable = 1
sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_group.select.page =  main,select * from (select a.* ,rownum row_num from (select wg.group_id, wg.group_name, wg.enable, wg.memo, wg.create_id, wg.corp_id,count(wgt.target_id) from wirelessinfo_group wg,wirelessinfo_group_target wgt where corp_id =${corp_id} and wgt.group_id(+)=wg.group_id and wg.enable=1 group by (wg.group_id, wg.group_name, wg.enable, wg.memo, wg.create_id, wg.corp_id))a ) b where  b.row_num between ? and ?

sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_release_target.delete =  main,delete from wirelessinfo_release_target t where t.release_id =? and t.group_id=?
sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_release_target.group.select =  main,select id, release_id,group_id from wirelessinfo_release_target where release_id=?

sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_release_target.insert =  main,insert into wirelessinfo_release_target(id, release_id,group_id,start_time,end_time) values(RELEASE_TARGET_SEQ_ID.nextval,?,?,?,?)


sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_group.binding.select.count = main,select count(*) from ( select t.group_id, t.group_name,t.enable,t.memo,t.target_count,wt.start_time,wt.end_time from (select wg.group_id, wg.group_name, wg.enable, wg.memo, count(wgt.target_id) as target_count from wirelessinfo_group wg, wirelessinfo_group_target wgt, wirelessinfo_release_target wrt where wrt.release_id=? and corp_id = ${corp_id} and wgt.group_id(+) = wg.group_id and wrt.group_id = wg.group_id and wg.enable = 1 group by (wg.group_id, wg.group_name, wg.enable, wg.memo)) t,wirelessinfo_release_target wt where wt.group_id=t.group_id and wt.release_id =?)
sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_group.binding.select.page = main,select * from (select a.* ,rownum row_num from (select t.group_id, t.group_name,t.enable,t.memo,t.target_count,wt.start_time,wt.end_time from (select wg.group_id, wg.group_name, wg.enable, wg.memo, count(wgt.target_id) as target_count from wirelessinfo_group wg, wirelessinfo_group_target wgt, wirelessinfo_release_target wrt where wrt.release_id=? and corp_id = ${corp_id} and wgt.group_id(+) = wg.group_id and wrt.group_id = wg.group_id and wg.enable = 1 group by (wg.group_id, wg.group_name, wg.enable, wg.memo)) t,wirelessinfo_release_target wt where wt.group_id=t.group_id and wt.release_id =?)a ) b where  b.row_num between ? and ?
sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_group.not_binding.select.count = main,select count(*) from(select wg.group_id, wg.group_name, wg.enable, wg.memo, count(wgt.target_id) from wirelessinfo_group wg, wirelessinfo_group_target   wgt, (select r.group_id from wirelessinfo_group r where r.group_id not in (select t.group_id from wirelessinfo_group t, wirelessinfo_release_target rt where rt.group_id = t.group_id and rt.release_id = ?)) t where wgt.group_id(+) = wg.group_id and wg.group_id = t.group_id and wg.corp_id = ${corp_id} and wg.enable = 1 group by (wg.group_id, wg.group_name, wg.enable, wg.memo))
sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_group.not_binding.select.page = main,select * from (select a.* ,rownum row_num from (select wg.group_id, wg.group_name, wg.enable, wg.memo, count(wgt.target_id) from wirelessinfo_group wg, wirelessinfo_group_target   wgt, (select r.group_id from wirelessinfo_group r where r.group_id not in (select t.group_id from wirelessinfo_group t, wirelessinfo_release_target rt where rt.group_id = t.group_id and rt.release_id = ?)) t where wgt.group_id(+) = wg.group_id and wg.group_id = t.group_id and wg.corp_id = ${corp_id} and wg.enable = 1 group by (wg.group_id, wg.group_name, wg.enable, wg.memo)) a ) b where  b.row_num between ? and ?
sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_release_op.states.update = main,update wirelessinfo_release_op t set  t.states=? where t.release_id=?
sql.wirelessinfo.wirelessinfo_publish_binding.wirelessinfo_group.value.select = main,select t.group_id, t.group_name,t.enable,t.memo,t.target_count,wt.start_time,wt.end_time from (select wg.group_id, wg.group_name, wg.enable, wg.memo, count(wgt.target_id) as target_count from wirelessinfo_group wg, wirelessinfo_group_target wgt, wirelessinfo_release_target wrt where wrt.release_id=? and corp_id = ${corp_id} and wgt.group_id(+) = wg.group_id and wrt.group_id = wg.group_id and wg.enable = 1 group by (wg.group_id, wg.group_name, wg.enable, wg.memo)) t,wirelessinfo_release_target wt where wt.group_id=t.group_id and wt.release_id =?




sql.wirelessinfo.wirelessinfo_publish_binding.select.count =  main,select count(*) from wirelessinfo_release_op wro where wro.corp_id =${corp_id} and wro.isdelete=0 and (wro.states = 3 or wro.states = 4)
sql.wirelessinfo.wirelessinfo_publish_binding.select.page =  main,select * from (select a.* ,rownum row_num from (select wr.release_id,wr.release_num,wr.content_type,wr.start_time,wr.end_time,wr.play_start_time,wr.play_end_time,wr.text,wr.customer_id,wr.states,wr.create_time,wr.cost,wr.info_class, wr.release_type,wr.reg_user_id,wr.release_cost, wr.path, wr.ref_release_id,wr.corp_id,wr.isdelete,wc.customer_name from wirelessinfo_release_op wr,wirelessinfo_customer wc where wc.customer_id=wr.customer_id and wr.isdelete=0 and (wr.states = 3 or wr.states = 4) and wr.corp_id =${corp_id} order by release_id asc ) a ) b where  b.row_num between ? and ?


